### ISSUE TITLE
Network error on 'node deploy.js' command on Ubuntu subsystem on Windows

### ISSUE THREAD

**Issue by eldnctlh** [PatrickAlphaC/ethers-simple-storage-fcc#13]
So im trying to run this command and getting this error
error fires right after conrtact.deploy()
```
  const contract = await contractFactory.deploy();
```
Here is the error: 
```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.8)
    at Logger.makeError (/home/andrey/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/andrey/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at JsonRpcProvider.<anonymous> (/home/andrey/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:561:54)
    at step (/home/andrey/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/andrey/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/andrey/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

Here is my code: 
```
const ethers = require("ethers");
const fs = require("fs-extra");

// yarn solcjs --bin --abi --include-path node_modules/ --base-path . -o . SimpleStorage.sol
// http://127.0.0.1:7545

async function main() {
  const provider = new ethers.providers.JsonRpcProvider(
    "http://127.0.0.1:7545"
  );
  const wallet = new ethers.Wallet(
    [wallet key goes here],
    provider
  );

  const abi = fs.readFileSync("./SimpleStorage_sol_SimpleStorage.abi", "utf8");
  const binary = fs.readFileSync(
    "./SimpleStorage_sol_SimpleStorage.bin",
    "utf8"
  );

  const contractFactory = new ethers.ContractFactory(abi, binary, wallet);
  console.log("Deploying...");
  const contract = await contractFactory.deploy();
  console.log(contract);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.log(err);
    process.exit(1);
  });
```

**Comment by eldnctlh** [comment]
Tried to run this code in pure Windows and its working, so the reason is Linux subsystem

**Comment by eldnctlh** [comment]
Fixed!
changed server host in ganache settings to wsl one
![image](https://user-images.githubusercontent.com/36642337/174485976-bf6ea2ff-7d46-4854-a526-33b96164bfe8.png)
