### ISSUE TITLE
Error: invalid JSON wallet

### ISSUE THREAD

**Issue by mitrang2022** [PatrickAlphaC/ethers-simple-storage-fcc#37]
Getting an Error while generating wallet from encrypted JSON.
Code:
```javascript
  let wallet = new ethers.Wallet.fromEncryptedJsonSync(
    encryptedJson,
    process.env.PRIVATE_KEY_PASS
  );
```
Error:
```
Error: invalid JSON wallet
    at decryptJsonWalletSync (/home/mitrang/Documents/hardhat-tutorial/hhFcc/ethersSimpleStorage/node_modules/@ethersproject/json-wallets/lib/index.js:38:11)
    at new Wallet.fromEncryptedJsonSync (/home/mitrang/Documents/hardhat-tutorial/hhFcc/ethersSimpleStorage/node_modules/@ethersproject/wallet/lib/index.js:229:68)
    at main (/home/mitrang/Documents/hardhat-tutorial/hhFcc/ethersSimpleStorage/deploy.js:10:16)
    at Object.<anonymous> (/home/mitrang/Documents/hardhat-tutorial/hhFcc/ethersSimpleStorage/deploy.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

The private key is properly encrypted in '.encryptedKey.json'. 
Can anyone please help?

deploy.js file: 
```javascript
const ethers = require("ethers");
const fs = require("fs-extra");
require("dotenv").config();

async function main() {
  const provider = new ethers.providers.JsonRpcProvider(process.env.RPC_URL);
  // const wallet = new ethers.Wallet(process.env.PRIVATE_KEY, provider);

  const encryptedJson = fs.read("./.encryptedKey.json", "utf8");
  let wallet = new ethers.Wallet.fromEncryptedJsonSync(
    encryptedJson,
    process.env.PRIVATE_KEY_PASS
  );
  wallet = await wallet.connect(provider);

  const abi = fs.readFileSync("./simpleStorage_sol_SimpleStorage.abi", "utf8");
  const binary = fs.readFileSync(
    "./simpleStorage_sol_SimpleStorage.bin",
    "utf8"
  );

  const contractFactory = new ethers.ContractFactory(abi, binary, wallet);
  console.log("Deploying...");
  const contract = await contractFactory.deploy();
  const TxReceipt = await contract.deployTransaction.wait(1);

  const currentFavNum = await contract.retrieve();
  console.log(`Current fav Num: ${currentFavNum.toString()}`);
  const transactionResponse = await contract.store("7");
  const transactionReceipt = await transactionResponse.wait(1);
  const updatedFavNum = await contract.retrieve();
  console.log(`Updated fav number is : ${updatedFavNum.toString()}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
```

**Comment by PatrickAlphaC** [comment]
This means you didn't encrypt your wallet correctly!

**Comment by apuser333** [comment]
I am getting the same error, did you find a solution yet?

**Comment by apuser333** [comment]
> This means you didn't encrypt your wallet correctly!

I am getting the same error, I have double checked the code. It was all working fine until I edited code for wallet in deploy.js

**Comment by RyanPaulGannon** [comment]
Also had the same issue today, have you made sure that you're encrypting the `PRIVATE_KEY_PASSWORD` before `PRIVATE_KEY`? 

```
async function main() {
  const wallet = new ethers.Wallet(process.env.PRIVATE_KEY);
  const encryptedKey = await wallet.encrypt(
    process.env.PRIVATE_KEY_PASSWORD,
    process.env.PRIVATE_KEY
  );
  console.log(encryptedKey);
  fs.writeFileSync('./.encryptedKey.json', encryptedKey);
}
```

**Comment by RyanPaulGannon** [comment]
Have you had any joy with this?

**Comment by PatrickAlphaC** [comment]
Going to close, looks like that was the issue.

**Comment by TechnoRahmon** [comment]
thanx  a lot, that helped me. 
I got the opposite error,  it was **invalid password** 
in my case, the issue was an invalid password because of the wrong order of arguments  for **encrypt()** method in the encrypt.js

this is the correct order:
```javascript
  const encryptedJsonKey = await wallet.encrypt(
    process.env.PRIVATE_KEY_PASSWORD,
    process.env.PRIVATE_KEY
    
  );
```
