### ISSUE TITLE
typescript error - Only a void function can be called with the 'new' keyword

### ISSUE THREAD

**Issue by TechnoRahmon** [PatrickAlphaC/ethers-simple-storage-fcc#50]
hi everyone

I am trying to switch to **ts** version of the deploy file in this course.

in the **deploy.ts**, I am using the decrypt method ``fromEncryptedJsonSync`` from the from ``ethers.Wallet``  ether js.
unfortunately it works with js but not in ts version. 

here is my code and my packages version:

```javascript

import {ethers } from 'ethers'
import dotenv from 'dotenv'
dotenv.config();
import * as fs from 'fs-extra';


// using Ganache desktop localy to get the a test wallet locally, getting the Private key from it
const ProviderRPC:string = process.env.PROVIDER_RPC !;
const PrivateKeyPassword:string = process.env.PRIVATE_KEY_PASSWORD!;
// abi - bin > files names
const AbiFileName = "SimpleStorage_sol_SimpleStorage.abi"
const BinFileName = "SimpleStorage_sol_SimpleStorage.bin"

async function main() {
    // main scipt to compile code
    //HTTP://127.0.0.1:7545

    // blockchain connection  ( network provider )
    const provider = new ethers.providers.JsonRpcProvider(ProviderRPC)
    //const wallet = new ethers.Wallet(PrivateKey, provider);
    //get the encryptedJsonKey object
    const encryptedJsonKey:string = fs.readFileSync("./.encryptedKey.json", "utf8")
    // decrypt the encryptedJsonKey object  throw passing the pasword  to get the wallet
    console.log(PrivateKeyPassword)
    let wallet:any= new ethers.Wallet.fromEncryptedJsonSync(
        encryptedJsonKey,
        PrivateKeyPassword
    )
    console.log(wallet)
    // connect the wallet with the provider
    wallet = await wallet.connect(provider)

    const abi = fs.readFileSync(`./${AbiFileName}`, "utf8")
    const bin = fs.readFileSync(`./${BinFileName}`, "utf8")

    const contractFactory = new ethers.ContractFactory(abi, bin, wallet)
    console.log("Deploying, Please wait ...")
    const contract = await contractFactory.deploy()
    // specifiy the number of block confirmation that it gonna wait
    await contract.deployTransaction.wait(1)
    console.log(`contract address : ${contract.address}`)

    // store a new favorite number
    const StoreTransactionReceipt = await contract.store("16")
    const StoreTransactionResp = await StoreTransactionReceipt.wait(1)

    // get the favorite number
    const currentFavoriteNumber = await contract.retrieve()
    console.log(`current Favorite Number : ${currentFavoriteNumber.toString()}`)
   
}

main()
    .then(() => {
        console.log("deployment Done!")
        process.exit(0)
    })
    .catch((error) => {
        console.error(error)
        process.exit(1)
    })


```
the issue is in the line  below : 
```javascript
    let wallet:any= new ethers.Wallet.fromEncryptedJsonSync(
        encryptedJsonKey,
        PrivateKeyPassword
    )
```
the error I am getting in my console
```error
deploy.ts:29:21 - error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.

29     let wallet:any= new ethers.Wallet.fromEncryptedJsonSync(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
30         encryptedJsonKey,
   ~~~~~~~~~~~~~~~~~~~~~~~~~
31         PrivateKeyPassword
   ~~~~~~~~~~~~~~~~~~~~~~~~~~
32     )
   ~~~~~

    at createTSError (/home/ub-rahmon/.nvm/versions/node/v16.14.2/lib/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/ub-rahmon/.nvm/versions/node/v16.14.2/lib/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/ub-rahmon/.nvm/versions/node/v16.14.2/lib/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/ub-rahmon/.nvm/versions/node/v16.14.2/lib/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/ub-rahmon/.nvm/versions/node/v16.14.2/lib/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ub-rahmon/.nvm/versions/node/v16.14.2/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  diagnosticCodes: [ 7009 ]
```
my package json file 
```json
{
  "dependencies": {
    "@types/fs-extra": "^9.0.13",
    "dotenv": "^16.0.3",
    "ethers": "5.5.3",
    "fs-extra": "^10.1.0",
    "prettier": "^2.7.1",
    "prettier-plugin-solidity": "^1.0.0-beta.24",
    "solc": "0.8.7-fixed",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4"
  },
  "scripts": {
    "deploy": "yarn solcjs --bin --abi --include-path node_modules/ --base-path . -o . SimpleStorage.sol"
  },
  "devDependencies": {
    "ethers-typescript-typings": "^0.0.4"
  }
}

```

I tried to look into the ``node_modules/@ethersproject/wallet/src.ts/index.ts`` file 
it gives punch of errors there too, I think maybe it's a typescript version issue or the **ethersjs** types not working well.
any ideas? :)

**Comment by TechnoRahmon** [comment]
### it worked with me 🎉 

the key is in the ``node_modules/@ethersproject/wallet/src.ts/index.ts`` file 
in the **fromEncryptedJsonSync** method, in typescript, they are returning `` new Wallet()`` 

```
    static fromEncryptedJsonSync(json: string, password: Bytes | string): Wallet {
        return new Wallet(decryptJsonWalletSync(json, password));
    }

```

so we don't need to make a new instance from **fromEncryptedJsonSync**  in the ``deoply.ts`` file as we do in the javascript version!! , instead, we call the static method directly!

so we actually need to remove the **new** keyword from our code when declaring the wallet variable, 
to be like this :

```javascript
    let wallet:any=  ethers.Wallet.fromEncryptedJsonSync(
        encryptedJsonKey,
        PrivateKeyPassword
    )
```

**Comment by shawnesquivel** [comment]
worked for me, big thanks Rahmon.
