### ISSUE TITLE
Running into a "NETWORK_ERROR" while deploying contract to Goerli

### ISSUE THREAD

**Issue by SuperGops7** [PatrickAlphaC/ethers-simple-storage-fcc#55]
So, I've been following the entire tutorial and was able to run the simple storage contract on Ganache. However, when I try to deploy the same on Goerli through Alchemy, I get this error:
```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/home/gopikk/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/gopikk/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at JsonRpcProvider.<anonymous> (/home/gopikk/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
    at step (/home/gopikk/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/gopikk/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/gopikk/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

I tried hardcoding the RPC URL and my PRIVATE KEY values into the provider and wallet functions, instead of getting them from the .env file, without any success. Is this an issue with Alchemy's API/ Goerli? Am I missing something?

**Comment by Milidrag** [comment]
@OceanHL thanks. Worked for me

**Comment by rakshithshenoy** [comment]
Heyy, I'm getting the same error as @SuperGops7 whenever I try to connect to Goerli test net. I was able to successfully deploy on Ganache but it doesn't work when I try with Alchemy or Infura URLs.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
