### ISSUE TITLE
Deploying the contract wont work. 7:07:25. Any help would be greatly appreciated.

### ISSUE THREAD

**Issue by egutierrez130** [PatrickAlphaC/ethers-simple-storage-fcc#63]
Hey all, for some reason, when I run this in the terminal --> node deploy.js   
It will not deploy the contract. 
It is throwing this TypeError: Cannot read properties of undefined (reading 'JsonRpcProvider')
at main (/Users/edgargutierrez/hh-fcc/ethers-simple-storage-fcc/deploy.js:8:41)
    at Object.<anonymous> (/Users/edgargutierrez/hh-fcc/ethers-simple-storage-fcc/deploy.js:18:1)

Any help would be greatly appreciated. 
ps. I have redone the lesson and made sure all code is correct. My guess is that something is now outdated since 0.8.7 was a long time ago.

**Comment by mishdgr8** [comment]
The newer version of Ethers seems to be unstable ethers 6.0.2... To solve this error downgrade your ethers version to 5.7.2 by going to your package.json

"ethers": "5.7.2",

now on your cli use npm install ethers@5.7.2 or yarn add ethers@5.7.2 depending on your package manager and that should solve your error.

**Comment by egutierrez130** [comment]
@mishdgr8 Thank you so much! This worked for me! I appreciate the help! Now I can move forward! Thank you again!

**Comment by rohitx01** [comment]
I did change the ethers version as mentioned but after that its throwing a new error:
'''
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
'''
pls help

**Comment by DengreSarthak** [comment]
Try this. Worked for me. 
Solution by Izmanovich
https://github.com/PatrickAlphaC/ethers-simple-storage-fcc/issues/17
