### ISSUE TITLE
TypeError: wallet.connect is not a function?

### ISSUE THREAD

**Issue by DylanCodesStuff** [PatrickAlphaC/ethers-simple-storage-fcc#64]
I'm at the 7 hour 45 minute mark in the video. All of the encryption seems to have gone well, however when I am trying to run "PRIVATE_KEY_PASSWORD =password node deploy.js" I am getting the error "TypeError: wallet.connect is not a function. I've searched around a lot but this has me stumped. It worked fine before (when it wasn't using the encrypted json wallet, not sure if this has anything to do with it, perhaps something did go wrong?).

`const ethers = require("ethers");
const fs = require("fs-extra");
require("dotenv").config();

async function main() {
  // http://127.0.0.1:7545
  const provider = new ethers.providers.JsonRpcProvider(process.env.RPC_URL);
  // console.log(process.env.PRIVATE_KEY);
  // const wallet = new ethers.Wallet(process.env.PRIVATE_KEY, provider);
  const encryptedJson = fs.readFileSync("./.encryptedKey.json", "utf8");
  let wallet = new ethers.Wallet.fromEncryptedJson(
    encryptedJson,
    process.env.PRIVATE_KEY_PASSWORD
  );
  wallet = await wallet.connect(provider);
  const abi = fs.readFileSync("./SimpleStorage_sol_SimpleStorage.abi", "utf8");
  const binary = fs.readFileSync(
    "./SimpleStorage_sol_SimpleStorage.bin",
    "utf8"
  );
  const contractFactory = new ethers.ContractFactory(abi, binary, wallet);
  console.log("Deploying, please wait...");
  const contract = await contractFactory.deploy(); //Stop here! wait for contract to deploy
  await contract.deployTransaction.wait(1);
  //Get number
  const currentFavoriteNumber = await contract.retrieve();
  console.log(`Current Favorite Number: ${currentFavoriteNumber.toString()}`);
  const transactionResponse = await contract.store("7");
  const transactionReciept = await transactionResponse.wait(1);
  const updatedFavoriteNumber = await contract.retrieve();
  console.log(`Updated favorite number is: ${updatedFavoriteNumber}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });`

`
TypeError: wallet.connect is not a function
    at main (/home/dylan/hh-fcc/ethers-simple-storage/deploy.js:15:25)
    at Object.<anonymous> (/home/dylan/hh-fcc/ethers-simple-storage/deploy.js:34:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
`

**Comment by DylanCodesStuff** [comment]
I found my error, I left line 11 as fromEncryptedJson instead of fromEncryptedJsonSync. Silly mistake.
