### ISSUE TITLE
could not detect network

### ISSUE THREAD

**Issue by themesaz** [PatrickAlphaC/ethers-simple-storage-fcc#8]
I am using ganache and did the same thing that the tutor in the video did. but I have this error:

`Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.8)
    at Logger.makeError (/home/amir/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/amir/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at JsonRpcProvider.<anonymous> (/home/amir/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:561:54)
    at step (/home/amir/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/amir/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/amir/hh-fcc/ethers-simple-storage/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}`

**Comment by IntelAdviseMark** [comment]
Try these:

https://github.com/smartcontractkit/full-blockchain-solidity-course-js/blob/main/chronological-updates.md#windows-wsl--ganache
