### ISSUE TITLE
2 weeks stuck on Deploy ethers-simple-storage-fcc

### ISSUE THREAD

**Issue by malommey** [PatrickAlphaC/ethers-simple-storage-fcc#80]
please help...
i cant Deploy my simple-storage-fcc on external Blockchain but when i deploy using the hardhat without Importing new network to my   Json package i had no issue deploying my contract and now im trying to Deploy to Ganache im stuck on here.. this  is the code snippet "

const { ethers } = require("ethers");
const fs = require ("fs-extra");

async function main(){
    const provider = new ethers.providers.JsonRPCprovider("http//:127.0.0.1:8545");

    const wallet = ethers.wallet("0xca20e913bd706a86816e3b25ad24655b1cab3938b7a7e5134283b0276e6c5e1d",
     provider);
     const abi = fs.readFileSync("./simpleStorage.sol_Simpletorage.abi",
      "utf8");
     const binary = fs.readFileSync("SimpleStorage.sol_SimpleStorage.bin",
      "utf8");
      const contractFactory = new ethers.ContractFactory(abi,binary,wallet);
      console.log("deploying please wait..");
      const contract = await contractFactory.deploy();

here is the error when i run node deploy.js...

"node deploy.js
TypeError: ethers.providers.JsonRPCProvider is not a constructor
    at main (/home/mutiu/ethers-simple-storage/deploy.js:9:22)
    at Object.<anonymous> (/home/mutiu/ethers-simple-storage/deploy.js:27:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47"

THANK YOU

**Comment by gracecampo** [comment]
The method call for ethers.js has changed and should use new ethers. JsonRpcProvider (process. env. RPC_URL). You can try it out

**Comment by GIRISHNP** [comment]
new version of package is not correct to connect ether to network
Try this --  
 yarn add ethers@5.7.2
even if it not works instead of using ubantu terminal use normal terminal it will work

**Comment by DMG-01** [comment]
> The method call for ethers.js has changed and should use new ethers. JsonRpcProvider (process. env. RPC_URL). You can try it out

please i am a little confused can you write it and use any value for the RPC_URL

**Comment by malommey** [comment]
for the RPC_URL, select the blockchain or testnet url you want to deploy to

**Comment by malommey** [comment]
> 
‘’’ solidity 
‘’’
thank you all for participating to help me on deploying  my contract to ganache

‘’’ let provider = new ethers.JsonRpcProvider(process.env.RPC_URL)

let wallet = new ethers.Wallet(process.env.PRIVATE_KEY,provider)

‘’’
the above code helped me to import my .env file on deploy.js

‘’’

Thank you All
